on: [push]
name: Tests
jobs:
    setup-and-tests:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   name: Build containers
                run: docker-compose build --build-arg UID=$(id -u) --build-arg GID=$(id -g)

            -   name: Composer install
                run: docker-compose run --rm php composer install --no-interaction

            -   name: Run Code Standards
                run: docker-compose run --rm -T php vendor/bin/phpcs

            -   name: Run Tests
                run: docker-compose run --rm -T php vendor/bin/phpunit

            -   name: Report Coverage
                run: docker-compose run --rm php -e COVERALLS_REPO_TOKEN -e GITHUB_REF -e GITHUB_ACTIONS \
                    -e GITHUB_RUN_ID -e GITHUB_EVENT_NAME php vendor/bin/php-coveralls -v
